/* Auto-generated by InterfaceWrapper. Do not edit by hand. */
#define WRAPPERFROMCTOSHARP_EXPORTS

#include "WrapperFromCToSharp.h"           /* wrapper API + original C types */
#include "Messages/IOCARDvare.h" /* static Phs_* physical structures */

WRAPPER_API AdiInt Wrapper_ConvertToPhysical(AdiInt msgId, AdiUInt8* intfPtr)
{
    return IOCARD_LCU_PR_ConvertToPhysical(msgId, intfPtr);
}

WRAPPER_API void Wrapper_ConvertToInterface(AdiInt msgId, AdiUInt8* intfPtr)
{
    IOCARD_LCU_PR_ConvertToInterface(msgId, intfPtr);
}

WRAPPER_API PHS_HDRONLYMESSAGEIO2LCU* Wrapper_Get_HDR_ONLY_MESSAGE_IO2LCU(void)
{
    return &Phs_hdronlymessageio2lcu;
}

WRAPPER_API AdiInt HDR_ONLY_MESSAGE_IO2LCU_ConvertToPhysical(PHS_HDRONLYMESSAGEIO2LCU* phsPtr, AdiUInt8* intfPtr)
{
    return HDR_ONLY_MESSAGE_IO2LCU_CONVERT_TO_PH(phsPtr, intfPtr);
}

WRAPPER_API void HDR_ONLY_MESSAGE_IO2LCU_ConvertToInterface(PHS_HDRONLYMESSAGEIO2LCU* phsPtr, AdiUInt8* intfPtr)
{
    HDR_ONLY_MESSAGE_IO2LCU_CONVERT_TO_IN(phsPtr, intfPtr);
}

WRAPPER_API PHS_HDRONLYMESSAGELCU2IO* Wrapper_Get_HDR_ONLY_MESSAGE_LCU2IO(void)
{
    return &Phs_hdronlymessagelcu2io;
}

WRAPPER_API AdiInt HDR_ONLY_MESSAGE_LCU2IO_ConvertToPhysical(PHS_HDRONLYMESSAGELCU2IO* phsPtr, AdiUInt8* intfPtr)
{
    return HDR_ONLY_MESSAGE_LCU2IO_CONVERT_TO_PH(phsPtr, intfPtr);
}

WRAPPER_API void HDR_ONLY_MESSAGE_LCU2IO_ConvertToInterface(PHS_HDRONLYMESSAGELCU2IO* phsPtr, AdiUInt8* intfPtr)
{
    HDR_ONLY_MESSAGE_LCU2IO_CONVERT_TO_IN(phsPtr, intfPtr);
}

WRAPPER_API PHS_KEEPALIVEMESSAGE* Wrapper_Get_KEEP_ALIVE_MESSAGE(void)
{
    return &Phs_keepalivemessage;
}

WRAPPER_API AdiInt KEEP_ALIVE_MESSAGE_ConvertToPhysical(PHS_KEEPALIVEMESSAGE* phsPtr, AdiUInt8* intfPtr)
{
    return KEEP_ALIVE_MESSAGE_CONVERT_TO_PH(phsPtr, intfPtr);
}

WRAPPER_API void KEEP_ALIVE_MESSAGE_ConvertToInterface(PHS_KEEPALIVEMESSAGE* phsPtr, AdiUInt8* intfPtr)
{
    KEEP_ALIVE_MESSAGE_CONVERT_TO_IN(phsPtr, intfPtr);
}

WRAPPER_API PHS_LOGDATAMESSAGE* Wrapper_Get_LOG_DATA_MESSAGE(void)
{
    return &Phs_logdatamessage;
}

WRAPPER_API AdiInt LOG_DATA_MESSAGE_ConvertToPhysical(PHS_LOGDATAMESSAGE* phsPtr, AdiUInt8* intfPtr)
{
    return LOG_DATA_MESSAGE_CONVERT_TO_PH(phsPtr, intfPtr);
}

WRAPPER_API void LOG_DATA_MESSAGE_ConvertToInterface(PHS_LOGDATAMESSAGE* phsPtr, AdiUInt8* intfPtr)
{
    LOG_DATA_MESSAGE_CONVERT_TO_IN(phsPtr, intfPtr);
}

WRAPPER_API PHS_NONCEMESSAGE* Wrapper_Get_NONCE_MESSAGE(void)
{
    return &Phs_noncemessage;
}

WRAPPER_API AdiInt NONCE_MESSAGE_ConvertToPhysical(PHS_NONCEMESSAGE* phsPtr, AdiUInt8* intfPtr)
{
    return NONCE_MESSAGE_CONVERT_TO_PH(phsPtr, intfPtr);
}

WRAPPER_API void NONCE_MESSAGE_ConvertToInterface(PHS_NONCEMESSAGE* phsPtr, AdiUInt8* intfPtr)
{
    NONCE_MESSAGE_CONVERT_TO_IN(phsPtr, intfPtr);
}

WRAPPER_API PHS_REQUESTSTATUSMESSAGE* Wrapper_Get_REQUEST_STATUS_MESSAGE(void)
{
    return &Phs_requeststatusmessage;
}

WRAPPER_API AdiInt REQUEST_STATUS_MESSAGE_ConvertToPhysical(PHS_REQUESTSTATUSMESSAGE* phsPtr, AdiUInt8* intfPtr)
{
    return REQUEST_STATUS_MESSAGE_CONVERT_TO_PH(phsPtr, intfPtr);
}

WRAPPER_API void REQUEST_STATUS_MESSAGE_ConvertToInterface(PHS_REQUESTSTATUSMESSAGE* phsPtr, AdiUInt8* intfPtr)
{
    REQUEST_STATUS_MESSAGE_CONVERT_TO_IN(phsPtr, intfPtr);
}

WRAPPER_API PHS_SERIALIO2LCUMESSAGE* Wrapper_Get_SERIAL_IO2LCU_MESSAGE(void)
{
    return &Phs_serialio2lcumessage;
}

WRAPPER_API AdiInt SERIAL_IO2LCU_MESSAGE_ConvertToPhysical(PHS_SERIALIO2LCUMESSAGE* phsPtr, AdiUInt8* intfPtr)
{
    return SERIAL_IO2LCU_MESSAGE_CONVERT_TO_PH(phsPtr, intfPtr);
}

WRAPPER_API void SERIAL_IO2LCU_MESSAGE_ConvertToInterface(PHS_SERIALIO2LCUMESSAGE* phsPtr, AdiUInt8* intfPtr)
{
    SERIAL_IO2LCU_MESSAGE_CONVERT_TO_IN(phsPtr, intfPtr);
}

WRAPPER_API PHS_SERIALLCU2IOMESSAGE* Wrapper_Get_SERIAL_LCU2IO_MESSAGE(void)
{
    return &Phs_seriallcu2iomessage;
}

WRAPPER_API AdiInt SERIAL_LCU2IO_MESSAGE_ConvertToPhysical(PHS_SERIALLCU2IOMESSAGE* phsPtr, AdiUInt8* intfPtr)
{
    return SERIAL_LCU2IO_MESSAGE_CONVERT_TO_PH(phsPtr, intfPtr);
}

WRAPPER_API void SERIAL_LCU2IO_MESSAGE_ConvertToInterface(PHS_SERIALLCU2IOMESSAGE* phsPtr, AdiUInt8* intfPtr)
{
    SERIAL_LCU2IO_MESSAGE_CONVERT_TO_IN(phsPtr, intfPtr);
}

WRAPPER_API PHS_SETDISCRETESMESSAGE* Wrapper_Get_SET_DISCRETES_MESSAGE(void)
{
    return &Phs_setdiscretesmessage;
}

WRAPPER_API AdiInt SET_DISCRETES_MESSAGE_ConvertToPhysical(PHS_SETDISCRETESMESSAGE* phsPtr, AdiUInt8* intfPtr)
{
    return SET_DISCRETES_MESSAGE_CONVERT_TO_PH(phsPtr, intfPtr);
}

WRAPPER_API void SET_DISCRETES_MESSAGE_ConvertToInterface(PHS_SETDISCRETESMESSAGE* phsPtr, AdiUInt8* intfPtr)
{
    SET_DISCRETES_MESSAGE_CONVERT_TO_IN(phsPtr, intfPtr);
}

WRAPPER_API PHS_SETSYSTEMSTATEMESSAGE* Wrapper_Get_SET_SYSTEM_STATE_MESSAGE(void)
{
    return &Phs_setsystemstatemessage;
}

WRAPPER_API AdiInt SET_SYSTEM_STATE_MESSAGE_ConvertToPhysical(PHS_SETSYSTEMSTATEMESSAGE* phsPtr, AdiUInt8* intfPtr)
{
    return SET_SYSTEM_STATE_MESSAGE_CONVERT_TO_PH(phsPtr, intfPtr);
}

WRAPPER_API void SET_SYSTEM_STATE_MESSAGE_ConvertToInterface(PHS_SETSYSTEMSTATEMESSAGE* phsPtr, AdiUInt8* intfPtr)
{
    SET_SYSTEM_STATE_MESSAGE_CONVERT_TO_IN(phsPtr, intfPtr);
}

WRAPPER_API PHS_STARTINTERFACEMESSAGE* Wrapper_Get_START_INTERFACE_MESSAGE(void)
{
    return &Phs_startinterfacemessage;
}

WRAPPER_API AdiInt START_INTERFACE_MESSAGE_ConvertToPhysical(PHS_STARTINTERFACEMESSAGE* phsPtr, AdiUInt8* intfPtr)
{
    return START_INTERFACE_MESSAGE_CONVERT_TO_PH(phsPtr, intfPtr);
}

WRAPPER_API void START_INTERFACE_MESSAGE_ConvertToInterface(PHS_STARTINTERFACEMESSAGE* phsPtr, AdiUInt8* intfPtr)
{
    START_INTERFACE_MESSAGE_CONVERT_TO_IN(phsPtr, intfPtr);
}

WRAPPER_API PHS_STATUSMESSAGE* Wrapper_Get_STATUS_MESSAGE(void)
{
    return &Phs_statusmessage;
}

WRAPPER_API AdiInt STATUS_MESSAGE_ConvertToPhysical(PHS_STATUSMESSAGE* phsPtr, AdiUInt8* intfPtr)
{
    return STATUS_MESSAGE_CONVERT_TO_PH(phsPtr, intfPtr);
}

WRAPPER_API void STATUS_MESSAGE_ConvertToInterface(PHS_STATUSMESSAGE* phsPtr, AdiUInt8* intfPtr)
{
    STATUS_MESSAGE_CONVERT_TO_IN(phsPtr, intfPtr);
}

WRAPPER_API PHS_STOPINTERFACEMESSAGE* Wrapper_Get_STOP_INTERFACE_MESSAGE(void)
{
    return &Phs_stopinterfacemessage;
}

WRAPPER_API AdiInt STOP_INTERFACE_MESSAGE_ConvertToPhysical(PHS_STOPINTERFACEMESSAGE* phsPtr, AdiUInt8* intfPtr)
{
    return STOP_INTERFACE_MESSAGE_CONVERT_TO_PH(phsPtr, intfPtr);
}

WRAPPER_API void STOP_INTERFACE_MESSAGE_ConvertToInterface(PHS_STOPINTERFACEMESSAGE* phsPtr, AdiUInt8* intfPtr)
{
    STOP_INTERFACE_MESSAGE_CONVERT_TO_IN(phsPtr, intfPtr);
}

WRAPPER_API PHS_TLONLYMESSAGEIO2LCU* Wrapper_Get_TL_ONLY_MESSAGE_IO2LCU(void)
{
    return &Phs_tlonlymessageio2lcu;
}

WRAPPER_API AdiInt TL_ONLY_MESSAGE_IO2LCU_ConvertToPhysical(PHS_TLONLYMESSAGEIO2LCU* phsPtr, AdiUInt8* intfPtr)
{
    return TL_ONLY_MESSAGE_IO2LCU_CONVERT_TO_PH(phsPtr, intfPtr);
}

WRAPPER_API void TL_ONLY_MESSAGE_IO2LCU_ConvertToInterface(PHS_TLONLYMESSAGEIO2LCU* phsPtr, AdiUInt8* intfPtr)
{
    TL_ONLY_MESSAGE_IO2LCU_CONVERT_TO_IN(phsPtr, intfPtr);
}

WRAPPER_API PHS_TLONLYMESSAGELCU2IO* Wrapper_Get_TL_ONLY_MESSAGE_LCU2IO(void)
{
    return &Phs_tlonlymessagelcu2io;
}

WRAPPER_API AdiInt TL_ONLY_MESSAGE_LCU2IO_ConvertToPhysical(PHS_TLONLYMESSAGELCU2IO* phsPtr, AdiUInt8* intfPtr)
{
    return TL_ONLY_MESSAGE_LCU2IO_CONVERT_TO_PH(phsPtr, intfPtr);
}

WRAPPER_API void TL_ONLY_MESSAGE_LCU2IO_ConvertToInterface(PHS_TLONLYMESSAGELCU2IO* phsPtr, AdiUInt8* intfPtr)
{
    TL_ONLY_MESSAGE_LCU2IO_CONVERT_TO_IN(phsPtr, intfPtr);
}

