// Auto-generated by InterfaceWrapper. Do not edit by hand.
using System;
using System.Diagnostics;
using System.Runtime.InteropServices;
using System.Threading;

namespace GenericSim
{
    /// <summary>Raises the Windows timer resolution to 1 ms while enabled so short
    /// sleeps (and therefore fast periodic sends) fire on time.</summary>
    public static class HighResClock
    {
        [DllImport("winmm.dll", EntryPoint = "timeBeginPeriod")] private static extern uint TimeBeginPeriod(uint ms);
        [DllImport("winmm.dll", EntryPoint = "timeEndPeriod")] private static extern uint TimeEndPeriod(uint ms);
        private static int _enabled;

        public static void Enable() { if (Interlocked.Exchange(ref _enabled, 1) == 0) TimeBeginPeriod(1); }
        public static void Disable() { if (Interlocked.Exchange(ref _enabled, 0) == 1) TimeEndPeriod(1); }
    }

    /// <summary>
    /// Drift-free periodic timer on a dedicated high-priority background thread.
    /// It sleeps for the bulk of each interval and spin-waits the last ~2 ms, giving
    /// millisecond cadence accuracy for intervals as small as a few ms (e.g. 10 ms).
    /// Ticks are scheduled on an absolute timeline (next += interval), so one late
    /// tick does not shift the following ones. The callback runs on the timer
    /// thread and must be thread-safe.
    /// </summary>
    public sealed class PrecisionTimer : IDisposable
    {
        private readonly double _intervalMs;
        private readonly Action _tick;
        private volatile bool _running = true;

        public PrecisionTimer(double intervalMs, Action tick)
        {
            _intervalMs = Math.Max(1.0, intervalMs);
            _tick = tick ?? throw new ArgumentNullException(nameof(tick));
            HighResClock.Enable();
            var thread = new Thread(Loop) { IsBackground = true, Priority = ThreadPriority.Highest, Name = "PrecisionTimer" };
            thread.Start();
        }

        private void Loop()
        {
            var clock = Stopwatch.StartNew();
            double next = _intervalMs;
            while (_running)
            {
                double remaining = next - clock.Elapsed.TotalMilliseconds;
                if (remaining > 4.0)
                {
                    // Coarse wait: sleep almost all of the remaining time (1 ms resolution).
                    Thread.Sleep((int)(remaining - 2.0));
                }
                else if (remaining > 0.05)
                {
                    // Fine wait: spin the last ~2 ms for sub-millisecond accuracy.
                    Thread.SpinWait(250);
                }
                else
                {
                    try { _tick(); }
                    catch { /* never break the cadence */ }
                    next += _intervalMs;
                    // After a long stall (breakpoint, suspend) resync instead of bursting.
                    if (next < clock.Elapsed.TotalMilliseconds - _intervalMs)
                        next = clock.Elapsed.TotalMilliseconds + _intervalMs;
                }
            }
        }

        public void Dispose() => _running = false;
    }
}
