// Auto-generated by InterfaceWrapper. Do not edit by hand.
using System;
using System.Collections.Generic;
using System.IO;

namespace GenericSim
{
    /// <summary>One message captured in a recording.</summary>
    public sealed class RecordedMessage
    {
        public DateTime Timestamp { get; init; }
        public bool IsOutgoing { get; init; }
        public int MessageId { get; init; }
        public byte[] Data { get; init; } = Array.Empty<byte>();
    }

    /// <summary>Row shown in the Record tab table.</summary>
    public sealed class RecordedMessageRow
    {
        public int Ordinal { get; set; }
        public string Time { get; set; } = string.Empty;
        public string Direction { get; set; } = string.Empty;
        public string Message { get; set; } = string.Empty;
        public int MessageId { get; set; }
        public int Bytes { get; set; }
        public string Hex { get; set; } = string.Empty;
        /// <summary>The raw payload, used to decode the fields when the row is clicked.</summary>
        public byte[] Data { get; set; } = Array.Empty<byte>();
    }

    /// <summary>
    /// Binary recording format:
    ///   header  : magic "GSRC" (4 bytes) + version (int32)
    ///   record  : timestamp ticks (int64), direction (byte: 1=TX 0=RX),
    ///             message id (int32), payload length (int32), payload bytes.
    /// </summary>
    public static class RecordingFile
    {
        public const string Magic = "GSRC";
        public const int Version = 1;

        public static void WriteHeader(BinaryWriter writer)
        {
            writer.Write(Magic.ToCharArray());
            writer.Write(Version);
        }

        public static void WriteRecord(BinaryWriter writer, RecordedMessage record)
        {
            writer.Write(record.Timestamp.Ticks);
            writer.Write(record.IsOutgoing ? (byte)1 : (byte)0);
            writer.Write(record.MessageId);
            writer.Write(record.Data.Length);
            writer.Write(record.Data);
        }

        public static List<RecordedMessage> Load(string path)
        {
            var records = new List<RecordedMessage>();
            using var reader = new BinaryReader(File.OpenRead(path));

            var magic = new string(reader.ReadChars(4));
            if (magic != Magic)
                throw new InvalidDataException("Not a GenericSim recording file (bad magic).");
            var version = reader.ReadInt32();
            if (version != Version)
                throw new InvalidDataException($"Unsupported recording version {version}.");

            while (reader.BaseStream.Position < reader.BaseStream.Length)
            {
                var ticks = reader.ReadInt64();
                var outgoing = reader.ReadByte() == 1;
                var messageId = reader.ReadInt32();
                var length = reader.ReadInt32();
                var data = reader.ReadBytes(length);
                records.Add(new RecordedMessage
                {
                    Timestamp = new DateTime(ticks),
                    IsOutgoing = outgoing,
                    MessageId = messageId,
                    Data = data
                });
            }
            return records;
        }
    }

    /// <summary>Streams incoming and outgoing messages into a recording file.</summary>
    public sealed class MessageRecorder : IDisposable
    {
        private readonly object _sync = new();
        private BinaryWriter? _writer;
        private string? _path;

        public bool IsRecording { get { lock (_sync) return _writer is not null; } }
        public int RecordedCount { get; private set; }

        public void Start(string path)
        {
            lock (_sync)
            {
                _writer?.Dispose();
                _writer = new BinaryWriter(File.Create(path));
                _path = path;
                RecordedCount = 0;
                RecordingFile.WriteHeader(_writer);
                _writer.Flush();
            }
        }

        /// <summary>Appends one message; safe to call from any thread and a no-op when idle.</summary>
        public void Record(bool outgoing, int messageId, byte[] data)
        {
            lock (_sync)
            {
                if (_writer is null) return;
                RecordingFile.WriteRecord(_writer, new RecordedMessage
                {
                    Timestamp = DateTime.Now,
                    IsOutgoing = outgoing,
                    MessageId = messageId,
                    Data = data
                });
                _writer.Flush();
                RecordedCount++;
            }
        }

        /// <summary>Stops recording and returns the file path.</summary>
        public string? Stop()
        {
            lock (_sync)
            {
                _writer?.Dispose();
                _writer = null;
                return _path;
            }
        }

        public void Dispose() => Stop();
    }
}
