// Auto-generated by InterfaceWrapper. Do not edit by hand.
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text.Json;
using System.Xml.Linq;

namespace GenericSim
{
    /// <summary>One scenario step: a message plus its own asynchronous send attributes.</summary>
    public sealed class ScenarioStepRow : INotifyPropertyChanged
    {
        private int _index;
        private string _message = string.Empty;
        private int _timeMs;
        private int _periodicIntervalMs = 1000;
        private bool _periodic;
        private int _maxMessages;
        private bool _isSleep;
        private bool _isResponse;
        private string _responseTrigger = string.Empty;
        private string _responseField = string.Empty;
        private string _responseValue = "0";

        /// <summary>The JSON prefix number; also the send order shown in the grid.</summary>
        public int Index { get => _index; set { _index = value; OnChanged(nameof(Index)); } }
        public string Message { get => _message; set { _message = value; OnChanged(nameof(Message)); } }
        /// <summary>Milliseconds from scenario start until the first send;
        /// for a Sleep step, the sleep duration.</summary>
        public int TimeMs { get => _timeMs; set { _timeMs = value; OnChanged(nameof(TimeMs)); } }
        /// <summary>Interval between periodic sends, in milliseconds.</summary>
        public int PeriodicIntervalMs { get => _periodicIntervalMs; set { _periodicIntervalMs = value; OnChanged(nameof(PeriodicIntervalMs)); } }
        public bool Periodic { get => _periodic; set { _periodic = value; OnChanged(nameof(Periodic)); OnChanged(nameof(SendType)); } }
        /// <summary>Number of periodic sends; 0 sends with no limit.</summary>
        public int MaxMessages { get => _maxMessages; set { _maxMessages = value; OnChanged(nameof(MaxMessages)); } }
        /// <summary>True for a Sleep operation step: TimeMs holds the sleep duration and
        /// every step after it is delayed by that amount when the scenario runs.</summary>
        public bool IsSleep { get => _isSleep; set { _isSleep = value; OnChanged(nameof(IsSleep)); OnChanged(nameof(SendType)); } }
        /// <summary>True for a Response operation step: when <see cref="ResponseTrigger"/> is
        /// received and <see cref="ResponseField"/> equals <see cref="ResponseValue"/>, the
        /// step's Message is sent with its saved field values.</summary>
        public bool IsResponse { get => _isResponse; set { _isResponse = value; OnChanged(nameof(IsResponse)); OnChanged(nameof(SendType)); } }
        /// <summary>The message that must be received to evaluate the response rule.</summary>
        public string ResponseTrigger { get => _responseTrigger; set { _responseTrigger = value; OnChanged(nameof(ResponseTrigger)); } }
        /// <summary>The field of the received message that is compared.</summary>
        public string ResponseField { get => _responseField; set { _responseField = value; OnChanged(nameof(ResponseField)); } }
        /// <summary>The expected value of the compared field.</summary>
        public string ResponseValue { get => _responseValue; set { _responseValue = value; OnChanged(nameof(ResponseValue)); } }
        public string SendType => IsSleep ? "Sleep" : IsResponse ? "Response" : Periodic ? "Periodic" : "One Time";
        /// <summary>The message field values saved in the step JSON file.</summary>
        public Dictionary<string, string>? FieldValues { get; set; }

        public event PropertyChangedEventHandler? PropertyChanged;
        private void OnChanged(string n) => PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(n));
    }

    /// <summary>
    /// Persists a scenario as a folder: Configuration.xml (the Intervals sections) plus one
    /// "{index}_{message}.json" file per step holding the message field values, e.g.
    /// "0_STATUS_MESSAGE.json, 1_NONCE_MESSAGE.json".
    /// </summary>
    public static class ScenarioStore
    {
        public const string ConfigurationFileName = "Configuration.xml";

        public static void Save(string folder, IReadOnlyList<ScenarioStepRow> steps)
        {
            Directory.CreateDirectory(folder);

            // Remove stale step files so the folder always mirrors the current scenario.
            foreach (var file in Directory.GetFiles(folder, "*.json"))
            {
                var name = Path.GetFileNameWithoutExtension(file);
                var underscore = name.IndexOf('_');
                if (underscore > 0 && int.TryParse(name[..underscore], out _))
                    File.Delete(file);
            }

            var root = new XElement("Intervals");
            for (int i = 0; i < steps.Count; i++)
            {
                var step = steps[i];
                root.Add(new XElement("section",
                    new XAttribute("index", i),
                    new XAttribute("time", step.TimeMs),
                    new XAttribute("periodicInterval", step.PeriodicIntervalMs),
                    new XAttribute("periodic", step.Periodic ? "true" : "false"),
                    new XAttribute("maxMessages", step.MaxMessages),
                    new XAttribute("sleep", step.IsSleep ? "true" : "false"),
                    new XAttribute("response", step.IsResponse ? "true" : "false"),
                    new XAttribute("responseTrigger", step.ResponseTrigger),
                    new XAttribute("responseField", step.ResponseField),
                    new XAttribute("responseValue", step.ResponseValue)));

                var json = JsonSerializer.Serialize(
                    step.FieldValues ?? new Dictionary<string, string>(),
                    new JsonSerializerOptions { WriteIndented = true });
                File.WriteAllText(Path.Combine(folder, $"{i}_{step.Message}.json"), json);
            }

            new XDocument(new XDeclaration("1.0", "utf-8", null), root)
                .Save(Path.Combine(folder, ConfigurationFileName));
        }

        public static List<ScenarioStepRow> Load(string folder)
        {
            var configPath = Path.Combine(folder, ConfigurationFileName);
            if (!File.Exists(configPath))
                throw new FileNotFoundException($"'{ConfigurationFileName}' was not found in {folder}.");

            var steps = new List<ScenarioStepRow>();
            var root = XDocument.Load(configPath).Root
                ?? throw new InvalidDataException("Configuration.xml has no root element.");

            foreach (var section in root.Elements("section"))
            {
                var index = ReadInt(section, "index", steps.Count);
                var step = new ScenarioStepRow
                {
                    Index = index,
                    TimeMs = ReadInt(section, "time", 0),
                    PeriodicIntervalMs = ReadInt(section, "periodicInterval", 0),
                    Periodic = string.Equals((string?)section.Attribute("periodic"), "true", StringComparison.OrdinalIgnoreCase),
                    MaxMessages = ReadInt(section, "maxMessages", 0),
                    IsSleep = string.Equals((string?)section.Attribute("sleep"), "true", StringComparison.OrdinalIgnoreCase),
                    IsResponse = string.Equals((string?)section.Attribute("response"), "true", StringComparison.OrdinalIgnoreCase),
                    ResponseTrigger = (string?)section.Attribute("responseTrigger") ?? string.Empty,
                    ResponseField = (string?)section.Attribute("responseField") ?? string.Empty,
                    ResponseValue = (string?)section.Attribute("responseValue") ?? "0"
                };

                // The JSON file prefixed with the index carries the message name and its values.
                var file = Directory.GetFiles(folder, index + "_*.json").FirstOrDefault();
                if (file is not null)
                {
                    step.Message = Path.GetFileNameWithoutExtension(file)[(index.ToString().Length + 1)..];
                    step.FieldValues = JsonSerializer.Deserialize<Dictionary<string, string>>(File.ReadAllText(file));
                }
                steps.Add(step);
            }
            return steps;
        }

        private static int ReadInt(XElement element, string attribute, int fallback) =>
            int.TryParse((string?)element.Attribute(attribute), NumberStyles.Integer,
                CultureInfo.InvariantCulture, out var value) ? value : fallback;
    }
}
