// Auto-generated by InterfaceWrapper. Do not edit by hand.
using System;
using System.Collections.Generic;
using System.IO.Ports;
using System.Linq;
using System.Net;
using System.Net.Sockets;
using System.Threading;
using System.Threading.Tasks;

namespace GenericSim
{
    /// <summary>Abstraction over the physical link (UDP, TCP client/server or RS232).</summary>
    public interface ITransport : IDisposable
    {
        string Description { get; }
        /// <summary>Number of connected peers (TCP server: clients; others: 1 when open).</summary>
        int ConnectionCount { get; }
        void Start();
        void Send(byte[] data);
        event Action<byte[], string>? DataReceived;
        event Action<string>? StatusChanged;
    }

    public sealed class UdpTransport : ITransport
    {
        private readonly int _localPort;
        private readonly string _remoteIp;
        private readonly int _remotePort;
        private UdpClient? _udp;
        private CancellationTokenSource? _cts;

        public UdpTransport(int localPort, string remoteIp, int remotePort)
        {
            _localPort = localPort;
            _remoteIp = remoteIp;
            _remotePort = remotePort;
        }

        public string Description => $"UDP local {_localPort} -> {_remoteIp}:{_remotePort}";
        public int ConnectionCount => _udp is null ? 0 : 1;
        public event Action<byte[], string>? DataReceived;
        public event Action<string>? StatusChanged;

        public void Start()
        {
            _udp = new UdpClient(_localPort);
            _cts = new CancellationTokenSource();
            _ = ReceiveLoopAsync(_udp, _cts.Token);
        }

        public void Send(byte[] data)
        {
            var udp = _udp ?? throw new InvalidOperationException("UDP is not started.");
            udp.Send(data, data.Length, _remoteIp, _remotePort);
        }

        private async Task ReceiveLoopAsync(UdpClient client, CancellationToken token)
        {
            while (!token.IsCancellationRequested)
            {
                try
                {
                    var result = await client.ReceiveAsync(token);
                    DataReceived?.Invoke(result.Buffer, result.RemoteEndPoint.ToString());
                }
                catch (OperationCanceledException) { break; }
                catch (ObjectDisposedException) { break; }
                catch (Exception ex) { StatusChanged?.Invoke("UDP RX error: " + ex.Message); break; }
            }
        }

        public void Dispose()
        {
            _cts?.Cancel();
            _udp?.Close();
            _udp?.Dispose();
            _udp = null;
        }
    }

    public sealed class TcpClientTransport : ITransport
    {
        private readonly string _remoteIp;
        private readonly int _remotePort;
        private TcpClient? _client;
        private NetworkStream? _stream;
        private CancellationTokenSource? _cts;
        private readonly object _writeLock = new();

        public TcpClientTransport(string remoteIp, int remotePort)
        {
            _remoteIp = remoteIp;
            _remotePort = remotePort;
        }

        public string Description => $"TCP client -> {_remoteIp}:{_remotePort}";
        public int ConnectionCount => _client?.Connected == true ? 1 : 0;
        public event Action<byte[], string>? DataReceived;
        public event Action<string>? StatusChanged;

        public void Start()
        {
            _client = new TcpClient();
            _client.Connect(_remoteIp, _remotePort);
            _stream = _client.GetStream();
            _cts = new CancellationTokenSource();
            var from = _client.Client.RemoteEndPoint?.ToString() ?? $"{_remoteIp}:{_remotePort}";
            _ = ReceiveLoopAsync(_stream, from, _cts.Token);
        }

        public void Send(byte[] data)
        {
            var stream = _stream ?? throw new InvalidOperationException("TCP is not connected.");
            // Serialize writes: periodic sends may arrive from several timer threads.
            lock (_writeLock) stream.Write(data, 0, data.Length);
        }

        private async Task ReceiveLoopAsync(NetworkStream stream, string from, CancellationToken token)
        {
            var buffer = new byte[65536];
            while (!token.IsCancellationRequested)
            {
                try
                {
                    int read = await stream.ReadAsync(buffer.AsMemory(), token);
                    if (read <= 0) { StatusChanged?.Invoke("TCP connection closed by remote."); break; }
                    DataReceived?.Invoke(buffer.AsSpan(0, read).ToArray(), from);
                }
                catch (OperationCanceledException) { break; }
                catch (ObjectDisposedException) { break; }
                catch (Exception ex) { StatusChanged?.Invoke("TCP RX error: " + ex.Message); break; }
            }
        }

        public void Dispose()
        {
            _cts?.Cancel();
            _stream?.Dispose();
            _client?.Close();
            _client = null;
        }
    }

    public sealed class TcpServerTransport : ITransport
    {
        private readonly int _localPort;
        private readonly object _sync = new();
        private readonly object _writeLock = new();
        private readonly List<TcpClient> _clients = new();
        private TcpListener? _listener;
        private CancellationTokenSource? _cts;

        public TcpServerTransport(int localPort) => _localPort = localPort;

        public string Description => $"TCP server on port {_localPort}";
        public int ConnectionCount { get { lock (_sync) return _clients.Count; } }
        public event Action<byte[], string>? DataReceived;
        public event Action<string>? StatusChanged;

        public void Start()
        {
            _listener = new TcpListener(IPAddress.Any, _localPort);
            _listener.Start();
            _cts = new CancellationTokenSource();
            _ = AcceptLoopAsync(_listener, _cts.Token);
        }

        public void Send(byte[] data)
        {
            List<TcpClient> clients;
            lock (_sync) clients = _clients.ToList();
            if (clients.Count == 0) throw new InvalidOperationException("No TCP client is connected.");
            // Serialize writes: periodic sends may arrive from several timer threads.
            lock (_writeLock)
            {
                foreach (var client in clients)
                {
                    try { client.GetStream().Write(data, 0, data.Length); }
                    catch (Exception ex) { StatusChanged?.Invoke("TCP TX error: " + ex.Message); }
                }
            }
        }

        private async Task AcceptLoopAsync(TcpListener listener, CancellationToken token)
        {
            while (!token.IsCancellationRequested)
            {
                try
                {
                    var client = await listener.AcceptTcpClientAsync(token);
                    lock (_sync) _clients.Add(client);
                    var from = client.Client.RemoteEndPoint?.ToString() ?? "client";
                    StatusChanged?.Invoke($"TCP client connected: {from}.");
                    _ = ReceiveLoopAsync(client, from, token);
                }
                catch (OperationCanceledException) { break; }
                catch (ObjectDisposedException) { break; }
                catch (Exception ex) { StatusChanged?.Invoke("TCP accept error: " + ex.Message); break; }
            }
        }

        private async Task ReceiveLoopAsync(TcpClient client, string from, CancellationToken token)
        {
            var buffer = new byte[65536];
            try
            {
                var stream = client.GetStream();
                while (!token.IsCancellationRequested)
                {
                    int read = await stream.ReadAsync(buffer.AsMemory(), token);
                    if (read <= 0) break;
                    DataReceived?.Invoke(buffer.AsSpan(0, read).ToArray(), from);
                }
            }
            catch (OperationCanceledException) { }
            catch (ObjectDisposedException) { }
            catch (Exception ex) { StatusChanged?.Invoke("TCP RX error: " + ex.Message); }
            lock (_sync) _clients.Remove(client);
            StatusChanged?.Invoke($"TCP client disconnected: {from}.");
            client.Close();
        }

        public void Dispose()
        {
            _cts?.Cancel();
            _listener?.Stop();
            lock (_sync)
            {
                foreach (var client in _clients) client.Close();
                _clients.Clear();
            }
        }
    }

    public sealed class SerialTransport : ITransport
    {
        private readonly string _portName;
        private readonly int _baudRate;
        private readonly Parity _parity;
        private readonly StopBits _stopBits;
        private SerialPort? _port;
        private readonly object _writeLock = new();

        public SerialTransport(string portName, int baudRate, Parity parity = Parity.None, StopBits stopBits = StopBits.One)
        {
            _portName = portName;
            _baudRate = baudRate;
            _parity = parity;
            _stopBits = stopBits;
        }

        public string Description => $"RS232 {_portName} @ {_baudRate} baud, {_parity} parity, {_stopBits} stop bits";
        public int ConnectionCount => _port?.IsOpen == true ? 1 : 0;
        public event Action<byte[], string>? DataReceived;
        public event Action<string>? StatusChanged;

        public void Start()
        {
            _port = new SerialPort(_portName, _baudRate, _parity, 8, _stopBits);
            _port.DataReceived += OnDataReceived;
            _port.Open();
        }

        public void Send(byte[] data)
        {
            var port = _port ?? throw new InvalidOperationException("RS232 port is not open.");
            // Serialize writes: periodic sends may arrive from several timer threads.
            lock (_writeLock) port.Write(data, 0, data.Length);
        }

        private void OnDataReceived(object sender, SerialDataReceivedEventArgs e)
        {
            try
            {
                var port = _port;
                if (port is null) return;
                int count = port.BytesToRead;
                if (count <= 0) return;
                var data = new byte[count];
                port.Read(data, 0, count);
                DataReceived?.Invoke(data, _portName);
            }
            catch (Exception ex) { StatusChanged?.Invoke("RS232 RX error: " + ex.Message); }
        }

        public void Dispose()
        {
            var port = _port;
            _port = null;
            if (port is not null)
            {
                port.DataReceived -= OnDataReceived;
                try { if (port.IsOpen) port.Close(); } catch { /* port already gone */ }
                port.Dispose();
            }
        }
    }
}
